// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqPyjZP-DOAzC_4SUb-M8DfP9UfRY72QY',
    appId: '1:560636982577:web:6f74592625a48a8789ac10',
    messagingSenderId: '560636982577',
    projectId: 'ifpi-app',
    authDomain: 'ifpi-app.firebaseapp.com',
    storageBucket: 'ifpi-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkqbEZ-q020wOXE--9HvLRD0wwlfMfbmc',
    appId: '1:560636982577:android:309accdbdda861d189ac10',
    messagingSenderId: '560636982577',
    projectId: 'ifpi-app',
    storageBucket: 'ifpi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBajqHSBatpDv9gySws2WmsS-cHsHeCEUU',
    appId: '1:560636982577:ios:c2f302aff49e958589ac10',
    messagingSenderId: '560636982577',
    projectId: 'ifpi-app',
    storageBucket: 'ifpi-app.firebasestorage.app',
    iosBundleId: 'com.example.appIfpi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBajqHSBatpDv9gySws2WmsS-cHsHeCEUU',
    appId: '1:560636982577:ios:c2f302aff49e958589ac10',
    messagingSenderId: '560636982577',
    projectId: 'ifpi-app',
    storageBucket: 'ifpi-app.firebasestorage.app',
    iosBundleId: 'com.example.appIfpi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqPyjZP-DOAzC_4SUb-M8DfP9UfRY72QY',
    appId: '1:560636982577:web:a5b2a12b0624fa5f89ac10',
    messagingSenderId: '560636982577',
    projectId: 'ifpi-app',
    authDomain: 'ifpi-app.firebaseapp.com',
    storageBucket: 'ifpi-app.firebasestorage.app',
  );
}
